{
 "title": "Анализ персонала и местоположения",
 "description": "Показывает колличество сотрудников в каждом отделе, средней зарплате в каждой компании и общем колличестве минут, проведенных в каждой локации",
 "time": { "from": "2023-12-17T18:26:00.000Z", "to": "2023-12-17T21:03:00.000Z" },
 "panels": [
  {
   "title": "Общее число должностей",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT id) AS total_positions\r\nFROM analytical.position;"
    }
   ]
  },
  {
   "title": "Общее кол-во работников",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_employees_count\r\nFROM analytical.employee;"
    }
   ]
  },
  {
   "title": "Общее число компаний",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT id) AS total_companies\r\nFROM analytical.company_branch;"
    }
   ]
  },
  {
   "title": "Персонал и время в должности",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  analytical.department.name AS Название_отдела,\r\n  COUNT(analytical.employee.id) AS Всего_сотрудников,\r\n  analytical.company_branch.name AS Название_филиала,\r\n  AVG(analytical.seniority.salary) AS Средняя_зарплата,\r\n  analytical.branch_location.city AS Город_расположения,\r\n  SUM(analytical.seniority.count_minutes_in_position) AS среднее_время_в_должности\r\nFROM analytical.employee\r\nJOIN analytical.seniority ON analytical.employee.id = analytical.seniority.employee_id\r\nJOIN analytical.department ON analytical.seniority.department_id = analytical.department.id\r\nJOIN analytical.company_branch ON analytical.seniority.company_branch_id = analytical.company_branch.id\r\nJOIN analytical.branch_location ON analytical.seniority.branch_location_id = analytical.branch_location.id\r\nGROUP BY Название_отдела, Название_филиала, Город_расположения\r\nORDER BY Всего_сотрудников DESC, Средняя_зарплата DESC, среднее_время_в_должности DESC;"
    }
   ]
  },
  {
   "title": "Продолжительность работы сотрудников в компании",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  analytical.department.name AS department_name,\r\n  AVG(analytical.seniority.count_minutes_in_position) AS average_tenure\r\nFROM analytical.seniority\r\nJOIN analytical.department ON analytical.seniority.department_id = analytical.department.id\r\nGROUP BY department_name\r\nORDER BY department_name;"
    }
   ]
  },
  {
   "title": "Средняя зарплата ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TO_TIMESTAMP(CONCAT(da.year, '-', da.month, '-', da.day, ' ', da.hour, ':', da.minute), 'YYYY-MM-DD HH24:MI') AS время,\r\n  AVG(s.salary) AS средняя_зарплата\r\nFROM analytical.seniority s\r\nJOIN analytical.date da ON s.date_id = da.id\r\nGROUP BY время\r\nORDER BY время;"
    }
   ]
  },
  {
   "title": "Среднее время",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TO_TIMESTAMP(CONCAT(da.year, '-', da.month, '-', da.day, ' ', da.hour, ':', da.minute), 'YYYY-MM-DD HH24:MI') AS время,\r\n  AVG(s.count_minutes_in_position) AS среднее_время_в_должности\r\nFROM analytical.seniority s\r\nJOIN analytical.date da ON s.date_id = da.id\r\nGROUP BY время\r\nORDER BY время;"
    }
   ]
  },
  {
   "title": "Средняя зарплата и время ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT p.name, (AVG(s.salary) - MIN(s.salary)) / (MAX(s.salary) - MIN(s.salary)) AS\r\n    \"Средняя зарплата\",\r\n    (AVG(s.count_minutes_in_position) - MIN(s.count_minutes_in_position)) / (MAX(s.count_minutes_in_position) - MIN(s.count_minutes_in_position)) AS\r\n        \"Среднее время в должности\"\r\nFROM analytical.seniority s JOIN analytical.position p on p.id = s.position_id GROUP BY p.name;"
    }
   ]
  },
  {
   "title": "Средняя зарплата  по должностям",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  p.name AS position,\r\n  AVG(s.salary) AS average_salary\r\nFROM analytical.seniority s\r\nJOIN analytical.position p ON s.position_id = p.id\r\nGROUP BY position\r\nORDER BY average_salary DESC;"
    }
   ]
  },
  {
   "title": "Средняя зарплата по отделам",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  d.name AS department,\r\n  AVG(s.salary) AS average_salary\r\nFROM analytical.seniority s\r\nJOIN analytical.department d ON s.department_id = d.id\r\nGROUP BY department;"
    }
   ]
  }
 ]
}